### ISSUE TITLE
Fix trackpad

### ISSUE THREAD

**Issue by baobaoit** [baobaoit/Asus-ROG-GL552VW-OC#1]
- [x] Enabled trackpad
- [x] Fix trackpad "Not found" in Settings
- [x] Gestures

**Comment by baobaoit** [comment]
After patched battery percentage, the trackpad section in the settings will recognize your trackpad.

**Comment by victorwitkamp** [comment]
> After patched battery percentage, the trackpad section in the settings will recognize your trackpad.

This is very interesting. This might help me get it working using hotpatching. I had almost everything working using hotpatching except trackpad.
