### ISSUE TITLE
nvidia working

### ISSUE THREAD

**Issue by rbc33** [baobaoit/Asus-ROG-GL552VW-OC#16]
has any one get nvidia working?

**Comment by rbc33** [comment]
come back to hackintosh, please

**Comment by baobaoit** [comment]
As I was mentioned here: https://github.com/baobaoit/Asus-ROG-GL552VW-OC/issues/14#issuecomment-991828187

> I no longer use Hackintosh, so I don't pay much attention to this repo.

Apple no longer supports the nvidia.

The laptop does not support nvidia on hackintosh.
